USE pttk_final;
INSERT INTO account (username, password) VALUES ('admin', 'jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=');
INSERT INTO fullname (firstname, lastname) VALUES ('Quang', 'Tran');
INSERT INTO phone (phonenum, type) VALUES ('0327170059', 'mobile');
INSERT INTO birth (day, month, years) VALUES ('24', '08', '2000');
INSERT INTO address (city, district, houseno) VALUES ('HN', 'TT', '02');
INSERT INTO user (accountID, fullnameID, phoneID, birthID, addressID, gender) VALUES (1, 1, 1, 1, 1, 'male');
INSERT INTO customer (userID, accountNum, IDUn, IP, IDVeri, MemberID) VALUES (1, '1234567', NULL, NULL, 1, 1);
INSERT INTO area (square, location) VALUES (100.8, 'HN');
INSERT INTO branch (name, numworkers, location) VALUES ('CS1', 20, 'MB');
INSERT INTO timesheet (date, status) VALUES ('9', '1');
INSERT INTO salarygrade (name, multiplier) VALUES ('CEO', 10.2);
INSERT INTO employee (areaID, userID, branchID, timesheetID, salarygradeID, salaries, starteddate, IDCEO, Profession) VALUES (1, 1, 1, 1, 1, 2000.0, '1/1/2020', 1, 'GS');
INSERT INTO pttk_final.payment (Fees, IDCOD, Currency, Names) VALUES (10000, 1, 'vnd', 'Hand by Hand');
INSERT INTO pttk_final.payment (Fees, IDInter, AccountNumber, Pwd, Names) VALUES (100000, 1, '1234567', '8888', 'WESTERN UNION');
INSERT INTO pttk_final.payment (Fees, IDCredit, CardNumber, Type, Names) VALUES (25000, 1, '109203583', 'visa', 'quang', 'VISA');
INSERT INTO pttk_final.shipment (Fees, Address, Names, IDEco, MaximumTime) VALUES (15000, 'HN', 'GHTK', 1, '7 days');
INSERT INTO pttk_final.shipment (Fees, Address, Names, IDSafe, Insurance) VALUES (25000, 'HN', 'ViettelPost', 1, 'BIDV');
INSERT INTO pttk_final.shipment (Fees, Address, Names, IDFast, Tax) VALUES (35000, 'HN', 'J&T Express', 1, 10000);
INSERT INTO pttk_final.voucher (Names, ExpiresDate, IDCons, Quantity) VALUES ('KM Thang 1', '16-9-2023', 1, 10000);
INSERT INTO pttk_final.voucher (Names, ExpiresDate, IDPer, Percentage) VALUES ('KM Thang 2', '5-4-2022', 1, 5);