CREATE DATABASE pttk_final;
USE pttk_final;

CREATE TABLE Customer (ID int(10) NOT NULL AUTO_INCREMENT, UserID int(10) NOT NULL, AccountNum varchar(255), IDUn int(10), IP varchar(255), IDVeri int(10), MemberID int(10), PRIMARY KEY (ID));
CREATE TABLE Account (ID int(10) NOT NULL AUTO_INCREMENT, Username varchar(255), Password varchar(255), PRIMARY KEY (ID));
CREATE TABLE Fullname (ID int(10) NOT NULL AUTO_INCREMENT, Firstname varchar(255), Lastname varchar(255), PRIMARY KEY (ID));
CREATE TABLE Phone (ID int(10) NOT NULL AUTO_INCREMENT, PhoneNum varchar(255), Type varchar(255), PRIMARY KEY (ID));
CREATE TABLE Address (ID int(10) NOT NULL AUTO_INCREMENT, City varchar(255), District varchar(255), Houseno varchar(255), PRIMARY KEY (ID));
CREATE TABLE Report (ID int(10) NOT NULL AUTO_INCREMENT, EmployeeID int(10) NOT NULL, CustomerID int(10) NOT NULL, TimeStamp varchar(255), NameProduct varchar(255), Reasons varchar(255), IDCus int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Favourite (ID int(10) NOT NULL AUTO_INCREMENT, CustomerID int(10) NOT NULL, NameProduct varchar(255), PRIMARY KEY (ID));
CREATE TABLE Birth (ID int(10) NOT NULL AUTO_INCREMENT, Day varchar(255), Month varchar(255), Years varchar(255), PRIMARY KEY (ID));
CREATE TABLE Cart (ID int(10) NOT NULL AUTO_INCREMENT, CustomerID int(10) NOT NULL, CreatedAt varchar(255), UpdatedAt varchar(255), TotalQuantity int(10), TotalPrice float, PRIMARY KEY (ID));
CREATE TABLE Bill (ID int(10) NOT NULL AUTO_INCREMENT, EmployeeID int(10) NOT NULL, OrderID int(10) NOT NULL, TotalPrice float NOT NULL, DateCreated varchar(255), TotalDiscount float NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Payment (ID int(10) NOT NULL AUTO_INCREMENT, Fees float NOT NULL, Names varchar(255), IDCOD int(10), Currency varchar(255), IDInter int(10), AccountNumber varchar(255), Pwd varchar(255), IDCredit int(10), CardNumber varchar(255), Type varchar(255), PRIMARY KEY (ID));
CREATE TABLE Shipment (ID int(10) NOT NULL AUTO_INCREMENT, Fees float NOT NULL, Address varchar(255), Names varchar(255), IDEco int(10), MaximumTime varchar(255), IDSafe int(10), Insurance varchar(255), IDFast int(10), Tax float, PRIMARY KEY (ID));
CREATE TABLE Voucher (ID int(10) NOT NULL AUTO_INCREMENT, Names varchar(255), ExpiresDate varchar(255), IDCons int(10), Quantity float, IDPer int(10), Percentage int(10), PRIMARY KEY (ID));
CREATE TABLE `Order` (ID int(10) NOT NULL AUTO_INCREMENT, CartID int(10) NOT NULL, ShipmentID int(10) NOT NULL, VoucherID int(10) NOT NULL, PaymentID int(10) NOT NULL, EmployeeID int(10) NOT NULL, `Date` varchar(255), PRIMARY KEY (ID));
CREATE TABLE Notification (ID int(10) NOT NULL AUTO_INCREMENT, EmployeeID int(10) NOT NULL, CustomerID int(10) NOT NULL, Context varchar(255), TimeStamp varchar(255), `From` varchar(255), PRIMARY KEY (ID));
CREATE TABLE Employee (ID int(10) NOT NULL AUTO_INCREMENT, AreaID int(10) NOT NULL, BranchID int(10) NOT NULL, TimesheetID int(10) NOT NULL, SalaryGradeID int(10) NOT NULL, UserID int(10) NOT NULL, Salaries float NOT NULL, StartedDate varchar(255), IDCEO int(10), Profession varchar(255), IDAcc int(10), ExpYears int(10), IDSto int(10), Experience varchar(255), IDSys varchar(255), WorkDays int(10), PRIMARY KEY (ID));
CREATE TABLE `User` (ID int(10) NOT NULL AUTO_INCREMENT, AccountID int(10) NOT NULL, FullnameID int(10) NOT NULL, PhoneID int(10) NOT NULL, BirthID int(10) NOT NULL, AddressID int(10) NOT NULL, Gender varchar(255), PRIMARY KEY (ID));
CREATE TABLE SalaryGrade (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(255), Multiplier float NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Timesheet (ID int(10) NOT NULL AUTO_INCREMENT, `Date` varchar(255), Status varchar(255), PRIMARY KEY (ID));
CREATE TABLE Branch (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(255), NumWorkers int(10) NOT NULL, Location varchar(255), PRIMARY KEY (ID));
CREATE TABLE Area (ID int(10) NOT NULL AUTO_INCREMENT, Square float NOT NULL, Location varchar(255), PRIMARY KEY (ID));
CREATE TABLE Book (ISBN int(10) NOT NULL AUTO_INCREMENT, EmployeeID int(10) NOT NULL, PublisherID int(10) NOT NULL, AuthorID int(10) NOT NULL, Title varchar(255), Summary varchar(255), Years int(10) NOT NULL, IDLN int(10), TranslateLanguage varchar(255), VolumeLN int(10), EditionsLN int(10), IDCom int(10), NameSeries varchar(255), Artists varchar(255), IDText int(10), NumberOfPages int(10), VolumeText int(10), EditionsText int(10), PRIMARY KEY (ISBN));
CREATE TABLE Bookitem (ID int(10) NOT NULL AUTO_INCREMENT, EmployeeID int(10) NOT NULL, BookID int(10) NOT NULL, Price float NOT NULL, Discount float NOT NULL, UploadDate varchar(255), InStock int(10) NOT NULL, Book int(10), PRIMARY KEY (ID));
CREATE TABLE Publisher (ID int(10) NOT NULL AUTO_INCREMENT, Address varchar(255), Name varchar(255), OperateYears int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Author (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(255), ShortBio varchar(255), Birth varchar(255), PRIMARY KEY (ID));
CREATE TABLE SearchHistory (ID int(10) NOT NULL AUTO_INCREMENT, CustomerID int(10) NOT NULL, TimeStamp varchar(255), Keywords varchar(255), PRIMARY KEY (ID));
CREATE TABLE Bookitem_Cart (BookitemID int(10) NOT NULL, CartID int(10) NOT NULL, PRIMARY KEY (BookitemID, CartID));
ALTER TABLE Report ADD CONSTRAINT FKReport553273 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Notification ADD CONSTRAINT FKNotificati657007 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Favourite ADD CONSTRAINT FKFavourite860755 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE SearchHistory ADD CONSTRAINT FKSearchHist481291 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee812063 FOREIGN KEY (BranchID) REFERENCES Branch (ID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee522443 FOREIGN KEY (AreaID) REFERENCES Area (ID);
ALTER TABLE Report ADD CONSTRAINT FKReport961478 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE Notification ADD CONSTRAINT FKNotificati799830 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE Bill ADD CONSTRAINT FKBill283312 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE `Order` ADD CONSTRAINT FKOrder900126 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE `Order` ADD CONSTRAINT FKOrder92191 FOREIGN KEY (PaymentID) REFERENCES Payment (ID);
ALTER TABLE `Order` ADD CONSTRAINT FKOrder661486 FOREIGN KEY (VoucherID) REFERENCES Voucher (ID);
ALTER TABLE `Order` ADD CONSTRAINT FKOrder751924 FOREIGN KEY (ShipmentID) REFERENCES Shipment (ID);
ALTER TABLE Book ADD CONSTRAINT FKBook666593 FOREIGN KEY (AuthorID) REFERENCES Author (ID);
ALTER TABLE Book ADD CONSTRAINT FKBook221643 FOREIGN KEY (PublisherID) REFERENCES Publisher (ID);
ALTER TABLE Cart ADD CONSTRAINT FKCart195823 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE `Order` ADD CONSTRAINT FKOrder795597 FOREIGN KEY (CartID) REFERENCES Cart (ID);
ALTER TABLE Book ADD CONSTRAINT FKBook277454 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE Bookitem ADD CONSTRAINT FKBookitem569368 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE `User` ADD CONSTRAINT FKUser921365 FOREIGN KEY (AccountID) REFERENCES Account (ID);
ALTER TABLE `User` ADD CONSTRAINT FKUser847543 FOREIGN KEY (AddressID) REFERENCES Address (ID);
ALTER TABLE `User` ADD CONSTRAINT FKUser908985 FOREIGN KEY (PhoneID) REFERENCES Phone (ID);
ALTER TABLE `User` ADD CONSTRAINT FKUser444730 FOREIGN KEY (BirthID) REFERENCES Birth (ID);
ALTER TABLE `User` ADD CONSTRAINT FKUser481364 FOREIGN KEY (FullnameID) REFERENCES Fullname (ID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee432674 FOREIGN KEY (TimesheetID) REFERENCES Timesheet (ID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee956042 FOREIGN KEY (SalaryGradeID) REFERENCES SalaryGrade (ID);
ALTER TABLE Bookitem ADD CONSTRAINT FKBookitem266530 FOREIGN KEY (BookID) REFERENCES Book (ISBN);
ALTER TABLE Bookitem_Cart ADD CONSTRAINT FKBookitem_C968561 FOREIGN KEY (BookitemID) REFERENCES Bookitem (ID);
ALTER TABLE Bookitem_Cart ADD CONSTRAINT FKBookitem_C20404 FOREIGN KEY (CartID) REFERENCES Cart (ID);
ALTER TABLE Customer ADD CONSTRAINT FKCustomer697196 FOREIGN KEY (UserID) REFERENCES `User` (ID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee402193 FOREIGN KEY (UserID) REFERENCES `User` (ID);
ALTER TABLE Bill ADD CONSTRAINT FKBill69969 FOREIGN KEY (OrderID) REFERENCES `Order` (ID);
